### ISSUE TITLE
bfs depth concern

### ISSUE THREAD

**Issue by BrannonKing** [jix/permutation_group_experiments#1]
Can you verify that this line is indented correctly?
https://github.com/jix/permutation_group_experiments/blob/6a1222c7fd38161b0e7f5d388859fc4d7a39f42e/schreiersims.py#L699

Also, that method, schreier_tree_bfs, always sets self.tree but doesn't always set self.tree_depth. Is that correct?

I need to optimize schreier_tree_bfs to run faster for my use case, which I can do once I'm sure it's correct. Also, your example description is fantastic.

**Comment by BrannonKing** [comment]
I realized that tree_depth is not actually used anywhere.

**Comment by BrannonKing** [comment]
In schreier_tree_bfs, are we able to use the depth value to start iterating at a later spot? Or have any other performance ideas for that method? What can we do to make it not be O(n^3) ?

**Comment by jix** [comment]
Where do you get $O(n^3)$ from?

**Comment by BrannonKing** [comment]
I was just guessing the order from the triple-nested loop.

**Comment by jix** [comment]
The outer loop has one iteration per point in the orbit, the middle loop one iteration per generator and the inner loop at most 2 iterations. That should be $O(n \log n)$ assuming $O(\log n)$ generators.

That is, if I weren't using `.pop(0)` which actually is $O(n)$ making this $O(n^2 \log n)$. This can be avoided by using `collection.deque` instead which offers a $O(1)$ `popleft()`. There might be more low hanging fruits like that elsewhere. As the comment at the top says, this code is not at all optimized for actual runtime performance.
